#!/bin/bash
echo "===================================================="
echo "Salvando os processos para a proxima reinicialização"
echo "===================================================="
pm2 save
